Added interpolation, improved Noise.
Added interpolation to Adsp via interpolation.h
Refactored Noise to use new interpolation functions.
Noise now correctly renders a preview in its plot.
Fixed a related assert.
NOTE TO SELF: if getting component.cpp:1918 errors, use .repaintAsync
instead of .repaint!
TODO: Finish more powerful envelope interpolation function.
TODO: Refactor Envelope to use new interpolation functions.